api-version: v1Beta
feedhandlers:
  - exchange: Phemex
    include_symbol: BTCUSD
order_placers:
  - exchange: Phemex
environment:
  - key: EXCHANGE_INSTANCE
    value-source: SYSTEM_ENV
  - key: EXCHANGE_ACCOUNT
    value: 9019590001
  - key: PHEMEX_API_KEY
    value-source: SYSTEM_ENV
  - key: PHEMEX_API_SECRET
    value-source: SYSTEM_ENV
  - key: EXTRA_OUTPUTS
    value: Position,TradeFlows,MovingAverageCrossover,PnL
strategies:
  - name: MovingAverageCrossover
    module: macross1
    strategy-class: MovingAverageCrossoverStrategy1
    environment:
      - key: TRADING_INSTRUMENT
        value: PHEMEX:BTCUSD
      - key: MACROSS_BIN_MINUTES
        value: 5
      - key: MACROSS_FAST_WINDOW
        value: 10
      - key: MACROSS_SLOW_WINDOW
        value: 30
      - key: MACROSS_STOP_PCT
        value: 2.0
      - key: MACROSS_QTY
        value: 100000
      - key: MACROSS_COOL_SECONDS
        value: 15
