apiVersion: batch/v1
kind: CronJob
metadata:
  name: behemoth-md-upload
spec:
  schedule: "@midnight"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: behemoth-md-upload
            image: cloudwallcapital/serenity:2021.06.06-b87
            command: ["/app/venv-py3/bin/python"]
            args: ["serenity/marketdata/batch/behemoth_main.py"]
            env:
            - name: POSTGRES_SERENITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: serenity-password
            - name: AZURE_CONNECT_STR
              valueFrom:
                secretKeyRef:
                  name: azure-secret-config
                  key: connect-str
            - name: SMTP_HOSTNAME
              value: serenity-postfix
            volumeMounts:
            - mountPath: /behemoth
              name: behemoth
          restartPolicy: OnFailure
          volumes:
            - name: behemoth
              persistentVolumeClaim:
                claimName: behemoth-pv-claim
